name: Boiler Test Run

on:
  schedule:
    # 17:10 MSK → 14:10 UTC
    - cron: "10 14 * * *"

  workflow_dispatch: {}  # ручной запуск

jobs:
  test_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run test temperature at 17:10 MSK
      if: github.event.schedule == '10 14 * * *'
      env:
        STOUT_LOGIN: ${{ secrets.STOUT_LOGIN }}
        STOUT_PASSWORD: ${{ secrets.STOUT_PASSWORD }}
      run: python boiler_api.py 8

    - name: Manual run (for testing)
      if: github.event_name == 'workflow_dispatch'
      env:
        STOUT_LOGIN: ${{ secrets.STOUT_LOGIN }}
        STOUT_PASSWORD: ${{ secrets.STOUT_PASSWORD }}
      run: python boiler_api.py 8
