name: Boiler Auto Control

on:
  schedule:
    - cron: "0 20 * * *"   # 23:00 MSK
    - cron: "0 4 * * *"    # 07:00 MSK
  workflow_dispatch:

jobs:
  set_temp_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Detect UTC hour
      run: |
        HOUR=$(date -u +"%H")
        echo "Current UTC hour: $HOUR"
        echo "HOUR=$HOUR" >> $GITHUB_ENV

    - name: Set night temperature (23:00 MSK / 20:00 UTC)
      if: env.HOUR == '20'
      env:
        STOUT_LOGIN: ${{ secrets.STOUT_LOGIN }}
        STOUT_PASSWORD: ${{ secrets.STOUT_PASSWORD }}
      run: |
        echo "Setting night temp 50°C"
        python boiler_api.py 50

    - name: Set morning temperature (07:00 MSK / 04:00 UTC)
      if: env.HOUR == '04'
      env:
        STOUT_LOGIN: ${{ secrets.STOUT_LOGIN }}
        STOUT_PASSWORD: ${{ secrets.STOUT_PASSWORD }}
      run: |
        echo "Setting morning temp 8°C"
        python boiler_api.py 8
